# Generated by Django 4.2 on 2023-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Дата рождения'),
        ),
    ]
